# Generated by Django 4.2.7 on 2023-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
